// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package test

import (
	fmt "fmt"
	_ "github.com/amsokol/protoc-gen-gotagger/proto/tagger"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	Val                  string   `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty" graphql:"name11,optional" bson:"name12,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type DataNested struct {
	XVal2Value           string   `protobuf:"bytes,1,opt,name=__val2_value,json=Val2Value,proto3" json:"__val2_value,omitempty" graphql:"name21,optional" bson:"name22,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DataNested) Reset()         { *m = DataNested{} }
func (m *DataNested) String() string { return proto.CompactTextString(m) }
func (*DataNested) ProtoMessage()    {}
func (*DataNested) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0}
}

func (m *DataNested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNested.Unmarshal(m, b)
}
func (m *DataNested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNested.Marshal(b, m, deterministic)
}
func (m *DataNested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNested.Merge(m, src)
}
func (m *DataNested) XXX_Size() int {
	return xxx_messageInfo_DataNested.Size(m)
}
func (m *DataNested) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNested.DiscardUnknown(m)
}

var xxx_messageInfo_DataNested proto.InternalMessageInfo

func (m *DataNested) GetXVal2Value() string {
	if m != nil {
		return m.XVal2Value
	}
	return ""
}

type DataNested_OneMore_Nested struct {
	Val3                 string   `protobuf:"bytes,1,opt,name=val3,proto3" json:"val3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DataNested_OneMore_Nested) Reset()         { *m = DataNested_OneMore_Nested{} }
func (m *DataNested_OneMore_Nested) String() string { return proto.CompactTextString(m) }
func (*DataNested_OneMore_Nested) ProtoMessage()    {}
func (*DataNested_OneMore_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 0}
}

func (m *DataNested_OneMore_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNested_OneMore_Nested.Unmarshal(m, b)
}
func (m *DataNested_OneMore_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNested_OneMore_Nested.Marshal(b, m, deterministic)
}
func (m *DataNested_OneMore_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNested_OneMore_Nested.Merge(m, src)
}
func (m *DataNested_OneMore_Nested) XXX_Size() int {
	return xxx_messageInfo_DataNested_OneMore_Nested.Size(m)
}
func (m *DataNested_OneMore_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNested_OneMore_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_DataNested_OneMore_Nested proto.InternalMessageInfo

func (m *DataNested_OneMore_Nested) GetVal3() string {
	if m != nil {
		return m.Val3
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "test.Data")
	proto.RegisterType((*DataNested)(nil), "test.Data.nested")
	proto.RegisterType((*DataNested_OneMore_Nested)(nil), "test.Data.nested.OneMore_Nested")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0x2c, 0x49,
	0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29, 0x49, 0x2d, 0x2e, 0x91, 0x12, 0x2e, 0x49,
	0x4c, 0x4f, 0x4f, 0x2d, 0xd2, 0x87, 0x50, 0x10, 0x29, 0xa5, 0x5b, 0x8c, 0x5c, 0x2c, 0x2e, 0x89,
	0x25, 0x89, 0x42, 0x1e, 0x5c, 0xcc, 0x65, 0x89, 0x39, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x4e,
	0x66, 0xb3, 0x5a, 0xe6, 0x31, 0x1b, 0xa6, 0x17, 0x25, 0x16, 0x64, 0x14, 0xe6, 0x58, 0x29, 0xe5,
	0x25, 0xe6, 0xa6, 0x1a, 0x1a, 0xea, 0xe4, 0x17, 0x94, 0x64, 0xe6, 0xe7, 0x25, 0xe6, 0x28, 0x29,
	0x24, 0x15, 0xe7, 0xe7, 0x41, 0x85, 0x8d, 0x74, 0xf2, 0x73, 0x33, 0x4b, 0x52, 0x73, 0x0b, 0x4a,
	0x2a, 0x95, 0x82, 0x40, 0x46, 0x48, 0xb5, 0x33, 0x72, 0xb1, 0xe5, 0xa5, 0x16, 0x97, 0xa4, 0xa6,
	0x08, 0x85, 0x73, 0xf1, 0xc4, 0xc7, 0x97, 0x25, 0xe6, 0x18, 0x81, 0x88, 0xd2, 0x54, 0xdc, 0xa6,
	0x1b, 0x61, 0x37, 0xdd, 0x08, 0xc5, 0x74, 0xce, 0xb0, 0xc4, 0x1c, 0xa3, 0x30, 0x90, 0x41, 0x52,
	0x2a, 0x5c, 0x7c, 0xfe, 0x79, 0xa9, 0xbe, 0xf9, 0x45, 0xa9, 0xf1, 0x7e, 0x10, 0xab, 0x84, 0xb8,
	0x58, 0xca, 0x12, 0x73, 0x8c, 0x21, 0x56, 0x04, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x3f, 0x1a, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xda, 0x4b, 0xa3, 0x0c, 0x01, 0x00, 0x00,
}
