// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

package test

import (
	fmt "fmt"
	_ "github.com/amsokol/protoc-gen-gotagger/proto/tagger"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Data struct {
	ValVvall string `protobuf:"bytes,1,opt,name=val_vvall,json=valVvall,proto3" json:"val_vvall,omitempty" graphql:"name11,optional" bson:"name12,omitempty"`
	// Types that are valid to be assigned to OneOf:
	//	*Data_A
	//	*Data_BJk
	OneOf                isData_OneOf `protobuf_oneof:"one_of" graphql:"withNewTags,optional"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-" bson:"-"`
	XXX_unrecognized     []byte       `json:"-" bson:"-"`
	XXX_sizecache        int32        `json:"-" bson:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetValVvall() string {
	if m != nil {
		return m.ValVvall
	}
	return ""
}

type isData_OneOf interface {
	isData_OneOf()
}

type Data_A struct {
	A string `protobuf:"bytes,5,opt,name=a,proto3,oneof" bson:"A"`
}

type Data_BJk struct {
	BJk int32 `protobuf:"varint,6,opt,name=b_jk,json=bJk,proto3,oneof" bson:"b_Jk"`
}

func (*Data_A) isData_OneOf() {}

func (*Data_BJk) isData_OneOf() {}

func (m *Data) GetOneOf() isData_OneOf {
	if m != nil {
		return m.OneOf
	}
	return nil
}

func (m *Data) GetA() string {
	if x, ok := m.GetOneOf().(*Data_A); ok {
		return x.A
	}
	return ""
}

func (m *Data) GetBJk() int32 {
	if x, ok := m.GetOneOf().(*Data_BJk); ok {
		return x.BJk
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Data) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Data_A)(nil),
		(*Data_BJk)(nil),
	}
}

type DataNested struct {
	XVal2Value           string   `protobuf:"bytes,1,opt,name=__val2_value,json=Val2Value,proto3" json:"__val2_value,omitempty" graphql:"name21,optional" bson:"name22,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DataNested) Reset()         { *m = DataNested{} }
func (m *DataNested) String() string { return proto.CompactTextString(m) }
func (*DataNested) ProtoMessage()    {}
func (*DataNested) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0}
}

func (m *DataNested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNested.Unmarshal(m, b)
}
func (m *DataNested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNested.Marshal(b, m, deterministic)
}
func (m *DataNested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNested.Merge(m, src)
}
func (m *DataNested) XXX_Size() int {
	return xxx_messageInfo_DataNested.Size(m)
}
func (m *DataNested) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNested.DiscardUnknown(m)
}

var xxx_messageInfo_DataNested proto.InternalMessageInfo

func (m *DataNested) GetXVal2Value() string {
	if m != nil {
		return m.XVal2Value
	}
	return ""
}

type DataNested_OneMore_Nested struct {
	Val3                 string   `protobuf:"bytes,1,opt,name=val3,proto3" json:"val3,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DataNested_OneMore_Nested) Reset()         { *m = DataNested_OneMore_Nested{} }
func (m *DataNested_OneMore_Nested) String() string { return proto.CompactTextString(m) }
func (*DataNested_OneMore_Nested) ProtoMessage()    {}
func (*DataNested_OneMore_Nested) Descriptor() ([]byte, []int) {
	return fileDescriptor_871986018790d2fd, []int{0, 0, 0}
}

func (m *DataNested_OneMore_Nested) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataNested_OneMore_Nested.Unmarshal(m, b)
}
func (m *DataNested_OneMore_Nested) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataNested_OneMore_Nested.Marshal(b, m, deterministic)
}
func (m *DataNested_OneMore_Nested) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataNested_OneMore_Nested.Merge(m, src)
}
func (m *DataNested_OneMore_Nested) XXX_Size() int {
	return xxx_messageInfo_DataNested_OneMore_Nested.Size(m)
}
func (m *DataNested_OneMore_Nested) XXX_DiscardUnknown() {
	xxx_messageInfo_DataNested_OneMore_Nested.DiscardUnknown(m)
}

var xxx_messageInfo_DataNested_OneMore_Nested proto.InternalMessageInfo

func (m *DataNested_OneMore_Nested) GetVal3() string {
	if m != nil {
		return m.Val3
	}
	return ""
}

func init() {
	proto.RegisterType((*Data)(nil), "test.Data")
	proto.RegisterType((*DataNested)(nil), "test.Data.nested")
	proto.RegisterType((*DataNested_OneMore_Nested)(nil), "test.Data.nested.OneMore_Nested")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor_871986018790d2fd) }

var fileDescriptor_871986018790d2fd = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x4b, 0xf3, 0x30,
	0x1c, 0xc7, 0x9f, 0x3c, 0xeb, 0xca, 0x16, 0xff, 0x20, 0xf1, 0x32, 0x0a, 0x4a, 0xa9, 0x0a, 0x3b,
	0x4c, 0xa5, 0x1d, 0x78, 0xf0, 0x66, 0xf1, 0x20, 0x03, 0x27, 0x54, 0xa9, 0xc7, 0xf0, 0x2b, 0x8b,
	0x5d, 0x6d, 0x9a, 0xd4, 0x36, 0x66, 0x78, 0x17, 0x7c, 0x0f, 0x1e, 0x7c, 0x61, 0xbe, 0x1a, 0x49,
	0x23, 0x8a, 0xa0, 0x97, 0x24, 0x24, 0xdf, 0x7c, 0x3e, 0x5f, 0x7e, 0x18, 0x2f, 0x40, 0xc1, 0x51,
	0xdd, 0x48, 0x25, 0x89, 0xa3, 0x58, 0xab, 0xbc, 0x6d, 0x05, 0x79, 0xce, 0x9a, 0x63, 0xbb, 0xd9,
	0xa7, 0xe0, 0xfd, 0x3f, 0x76, 0xce, 0x41, 0x01, 0xb9, 0xc6, 0x43, 0x0d, 0x9c, 0x6a, 0x0d, 0x9c,
	0x8f, 0x90, 0x8f, 0xc6, 0xc3, 0xf8, 0xe4, 0xf5, 0xf9, 0xad, 0x17, 0xe6, 0x0d, 0xd4, 0xcb, 0x07,
	0x7e, 0x1a, 0x08, 0xa8, 0x58, 0x18, 0x4e, 0x64, 0xad, 0x0a, 0x29, 0x80, 0x07, 0x7e, 0xd6, 0x4a,
	0xf1, 0x79, 0x1d, 0x4d, 0x64, 0x55, 0x28, 0x56, 0xd5, 0xea, 0x29, 0x48, 0x06, 0x1a, 0x78, 0x6a,
	0x38, 0x64, 0x07, 0x23, 0x18, 0xf5, 0x3b, 0xd8, 0x86, 0x81, 0x0d, 0xec, 0x97, 0xb3, 0xe0, 0xe2,
	0x5f, 0x82, 0x80, 0x1c, 0x60, 0x27, 0xa3, 0xf7, 0xe5, 0xc8, 0xf5, 0xd1, 0xb8, 0x1f, 0x6f, 0x99,
	0xc4, 0x9a, 0x4d, 0x64, 0x74, 0x56, 0x9a, 0x50, 0x2f, 0x9b, 0x95, 0xde, 0x0b, 0xc2, 0xae, 0x60,
	0xad, 0x62, 0x0b, 0x72, 0x8b, 0xd7, 0x29, 0xd5, 0xc0, 0x23, 0xb3, 0x3c, 0xb2, 0xbf, 0x8b, 0x46,
	0xbf, 0x17, 0x8d, 0x7e, 0x14, 0x1d, 0xa6, 0xc0, 0xa3, 0xd4, 0x80, 0xbc, 0x7d, 0xbc, 0x79, 0x25,
	0xd8, 0xa5, 0x6c, 0x18, 0x9d, 0x5b, 0x15, 0xc1, 0x8e, 0x06, 0x3e, 0xb5, 0x8a, 0xa4, 0x3b, 0xc7,
	0x87, 0xd8, 0x95, 0x82, 0x51, 0x79, 0x47, 0xf6, 0x8c, 0x72, 0xf7, 0x4b, 0xb9, 0x2a, 0xd4, 0x72,
	0xce, 0x56, 0x37, 0x90, 0xb7, 0xdf, 0xde, 0xcc, 0xed, 0x66, 0x3c, 0xfd, 0x08, 0x00, 0x00, 0xff,
	0xff, 0xbe, 0xa6, 0xa0, 0x12, 0x8c, 0x01, 0x00, 0x00,
}
